# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca83a5e7bc910bc2225533fda0eed51620c4f5d1b95332b51ceba381b9b9b2e18fef7e00dbea6c95b997f4cb886d3d80d87a360009dc8e4c5205856da25ce00c

test:
  secret_key_base: 34eae88d6d7b9cd7f0df4727592f1ef8694f2aec2689feb823105b7273e59e1f132f5fe65898a2389333456bcbdb4741fa617ad20a8b252c273649ba2d14c9d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
